version: '3'
services:
  redis-server:
    image: 'redis'
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - 'redis-data:/data'
  node-app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - '/app/node_modules'
      - '.:/app'

volumes:
  redis-data:

